[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'self' https://*.myshopify.com https://*.shopify.com https://thisbrandgives.com"
